### ISSUE TITLE
Taskbook throws TypeError by wrong argument(like 1,2,3) for check

### ISSUE THREAD

**Issue by inabajunmr** [klaussinani/taskbook#99]
**Describe the bug**
Taskbook throws TypeError by wrong argument(like 1,2,3) for check.

**To Reproduce**
1. create 2 tasks
2. check 2 tasks with comma separator

```
$ tb -t test1
$ tb -t test2
$ tb -c 1,2
/usr/local/lib/node_modules/taskbook/lib/taskbook.js:312
      _data[id].isComplete = !_data[id].isComplete;
                                        ^

TypeError: Cannot read property 'isComplete' of undefined
    at ids.forEach.id (/usr/local/lib/node_modules/taskbook/lib/taskbook.js:312:41)
    at Array.forEach (<anonymous>)
    at Taskbook.checkTasks (/usr/local/lib/node_modules/taskbook/lib/taskbook.js:311:9)
    at taskbookCLI (/usr/local/lib/node_modules/taskbook/index.js:27:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/taskbook/cli.js:68:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Expected behavior**
print appropriate error message.

**Technical Info (please complete the following information)**
 - OS: macOS High Sierra 10.13.6（17G65）
 - Node.js Version: v8.9.1
 - Taskbook Version: 0.1.1

**Comment by klaussinani** [comment]
Try running the command while using whitespace as a delimiter:

```
$ tb -t test1
$ tb -t test2
$ tb -c 1 2
```
